var data = {
    "bookmarkedItem": [
    {
        "custom": "",
        "endDateTime": "",
        "markDateTime": "19/07/30 11:45:12",
        "selectableItem": [
            {
                "actor": "",
                "actorsDisplay": "王景春/咏梅/齐溪",
                "assetFileList": "",
                "assetId": "TWSX1559890321424272",
                "assetType": "",
                "bitrateList": "",
                "bookmarkDate": "",
                "chapter": "1",
                "chargeMode": "",
                "columnChargeMode": "",
                "columnPath": "/MSCP栏目/优酷/电影",
                "columnResourcePrice": "",
                "columnServiceId": "",
                "createTime": "",
                "currentChapter": "0",
                "detailLinkUrl": "",
                "detailURI": "",
                "director": [
                    {
                        "directorImageURL": "",
                        "name": "王小帅"
                    }
                ],
                "displayFlags": "",
                "displayRunTime": "10468s",
                "endDateTime": "",
                "favorRating": "0",
                "flagImageUrl": "",
                "folderAssetId": "MANU0000000000050440",
                "folderName": "电影",
                "freeChapter": "",
                "hasCollect": "",
                "hasRecommand": "",
                "imageList": [
                    {
                        "height": "358",
                        "posterUrl": "poster_root/20190607/TWSX1559890321424272/266x358/20190607145305665_4773.jpg",
                        "rank": "1",
                        "width": "266"
                    }
                ],
                "imageLocation": "",
                "initialLetter": "",
                "initialLetterToNumber": "",
                "isPackage": "0",
                "openTime": "",
                "orderNumber": "0",
                "originName": "中国大陆",
                "previewAssetId": "",
                "previewProviderId": "",
                "prividerName": "",
                "produceDate": "",
                "producter": "",
                "providerId": "qx_youku",
                "publishDate": "",
                "rating": "",
                "recommandRating": "0.0",
                "recommandTimes": "0",
                "recommendImage": "",
                "recommendLevel": "",
                "remark": "",
                "rentaInfo": "",
                "resourceId": "103749571",
                "resourceType": "0",
                "runtime": "02:54:28",
                "secondTitleFull": "",
                "selectionChoice": [
                    {
                        "audioType": "",
                        "displayPrice": "30",
                        "format": "HD",
                        "languageSet": "",
                        "rentalPeriod": "174",
                        "screenShape": "",
                        "viewLimit": "0"
                    }
                ],
                "serviceId": "testbycp",
                "serviceType": "VOD",
                "showType": "1",
                "startDateTime": "",
                "status": "1",
                "subscription": {
                    "chargeMode": "",
                    "enableTime": "",
                    "expireDateTime": "",
                    "productCode": "",
                    "productName": "",
                    "status": "0",
                    "subscribeTime": "",
                    "subscribeType": ""
                },
                "summarMedium": "",
                "summarvShort": "影片讲述患难与共的两个家庭因为一场有隐情的意外被迫疏远，他们在时代洪流下历尽伤痛与不安，人生起伏跌宕，最终选择面对真相，坦荡向前的故事。",
                "tailTime": "",
                "titleBrief": "",
                "titleFull": "地久天长",
                "videoType": "1",
                "viewLevel": "0",
                "year": "0"
            }
        ]
    },
    {
        "custom": "",
        "endDateTime": "",
        "markDateTime": "19/07/30 11:42:13",
        "selectableItem": [
            {
                "actor": "",
                "actorsDisplay": "舒贵林;孙书博;李则慧",
                "assetFileList": "",
                "assetId": "TWSX1560133092510948",
                "assetType": "",
                "bitrateList": "",
                "bookmarkDate": "",
                "chapter": "1",
                "chargeMode": "",
                "columnChargeMode": "",
                "columnPath": "/MSCP栏目/优酷/电影",
                "columnResourcePrice": "",
                "columnServiceId": "",
                "createTime": "",
                "currentChapter": "0",
                "detailLinkUrl": "",
                "detailURI": "",
                "director": [
                    {
                        "directorImageURL": "",
                        "name": "张高境"
                    }
                ],
                "displayFlags": "",
                "displayRunTime": "5168s",
                "endDateTime": "",
                "favorRating": "0",
                "flagImageUrl": "",
                "folderAssetId": "MANU0000000000050440",
                "folderName": "电影",
                "freeChapter": "",
                "hasCollect": "",
                "hasRecommand": "",
                "imageList": [
                    {
                        "height": "358",
                        "posterUrl": "poster_root/20190610/TWSX1560133092510948/266x358/20190610101916063_4781.jpg",
                        "rank": "1",
                        "width": "266"
                    }
                ],
                "imageLocation": "",
                "initialLetter": "",
                "initialLetterToNumber": "",
                "isPackage": "0",
                "openTime": "",
                "orderNumber": "0",
                "originName": "???",
                "previewAssetId": "",
                "previewProviderId": "",
                "prividerName": "",
                "produceDate": "",
                "producter": "",
                "providerId": "qx_youku",
                "publishDate": "",
                "rating": "",
                "recommandRating": "0.0",
                "recommandTimes": "0",
                "recommendImage": "",
                "recommendLevel": "",
                "remark": "",
                "rentaInfo": "",
                "resourceId": "103750095",
                "resourceType": "0",
                "runtime": "01:26:08",
                "secondTitleFull": "",
                "selectionChoice": [
                    {
                        "audioType": "",
                        "displayPrice": "30",
                        "format": "HD",
                        "languageSet": "",
                        "rentalPeriod": "86",
                        "screenShape": "",
                        "viewLimit": "0"
                    }
                ],
                "serviceId": "testbycp",
                "serviceType": "VOD",
                "showType": "1",
                "startDateTime": "",
                "status": "1",
                "subscription": {
                    "chargeMode": "",
                    "enableTime": "",
                    "expireDateTime": "",
                    "productCode": "",
                    "productName": "",
                    "status": "0",
                    "subscribeTime": "",
                    "subscribeType": ""
                },
                "summarMedium": "",
                "summarvShort": "新学期来临，东都卫校仅有的两个男生王子、张晓晓，在校长室打扫卫生时捅了个“大窟窿”，遭到处分还危及到了以后卫校男生的前途。王子决定争取拿到代表学校参加南丁格尔大赛的名额挽回过失。次日迎新，东都卫校又多了一名男生徐浪。卫校三男与新生毕夏（女）被迫组成“男团”。",
                "tailTime": "",
                "titleBrief": "",
                "titleFull": "卫校男生：青春反击战",
                "videoType": "1",
                "viewLevel": "7",
                "year": "0"
            }
        ]
    },
    {
        "custom": "",
        "endDateTime": "",
        "markDateTime": "19/07/30 11:41:11",
        "selectableItem": [
            {
                "actor": "",
                "actorsDisplay": "古天乐;郑嘉颖;林峯;林家栋;周秀娜",
                "assetFileList": "",
                "assetId": "TWSX1559005242129528",
                "assetType": "",
                "bitrateList": "",
                "bookmarkDate": "",
                "chapter": "1",
                "chargeMode": "",
                "columnChargeMode": "",
                "columnPath": "/MSCP栏目/优酷/电影",
                "columnResourcePrice": "",
                "columnServiceId": "",
                "createTime": "",
                "currentChapter": "0",
                "detailLinkUrl": "",
                "detailURI": "",
                "director": [
                    {
                        "directorImageURL": "",
                        "name": "林德禄"
                    }
                ],
                "displayFlags": "",
                "displayRunTime": "5838s",
                "endDateTime": "",
                "favorRating": "0",
                "flagImageUrl": "",
                "folderAssetId": "MANU0000000000050440",
                "folderName": "电影",
                "freeChapter": "",
                "hasCollect": "",
                "hasRecommand": "",
                "imageList": [
                    {
                        "height": "358",
                        "posterUrl": "poster_root/20190528/TWSX1559005242129528/266x358/20190528163756542_4756.jpg",
                        "rank": "1",
                        "width": "266"
                    }
                ],
                "imageLocation": "",
                "initialLetter": "",
                "initialLetterToNumber": "",
                "isPackage": "0",
                "openTime": "",
                "orderNumber": "0",
                "originName": "中国大陆",
                "previewAssetId": "",
                "previewProviderId": "",
                "prividerName": "",
                "produceDate": "",
                "producter": "",
                "providerId": "qx_youku",
                "publishDate": "",
                "rating": "",
                "recommandRating": "0.0",
                "recommandTimes": "0",
                "recommendImage": "",
                "recommendLevel": "",
                "remark": "",
                "rentaInfo": "",
                "resourceId": "103745866",
                "resourceType": "0",
                "runtime": "01:37:18",
                "secondTitleFull": "",
                "selectionChoice": [
                    {
                        "audioType": "",
                        "displayPrice": "30",
                        "format": "HD",
                        "languageSet": "",
                        "rentalPeriod": "97",
                        "screenShape": "",
                        "viewLimit": "0"
                    }
                ],
                "serviceId": "testbycp",
                "serviceType": "VOD",
                "showType": "1",
                "startDateTime": "",
                "status": "1",
                "subscription": {
                    "chargeMode": "",
                    "enableTime": "",
                    "expireDateTime": "",
                    "productCode": "",
                    "productName": "",
                    "status": "0",
                    "subscribeTime": "",
                    "subscribeType": ""
                },
                "summarMedium": "",
                "summarvShort": "廉政公署收到报案人廖雨萍（周秀娜饰）的实名举报，举报正在坐牢的富二代曹元元（林峯饰）涉嫌行贿监狱里的监督沈济全（谭耀文饰）以及惩教员，首席调查主任陆志廉（古天乐饰）决定深入虎穴，卧底狱中。在监狱里，被陆志廉送入监狱的前警司黄文彬（林家栋饰）以及曹元元两大帮派势成水火，陆志廉趁机接近曹元元取得信任。",
                "tailTime": "",
                "titleBrief": "",
                "titleFull": "反贪风暴4",
                "videoType": "1",
                "viewLevel": "0",
                "year": "0"
            }
        ]
    },
    {
        "custom": "",
        "endDateTime": "",
        "markDateTime": "19/07/30 11:39:27",
        "selectableItem": [
            {
                "actor": "",
                "actorsDisplay": "郑爽;英迪帕·塔尼;虞祎杰",
                "assetFileList": "",
                "assetId": "TWSX1562034209304778",
                "assetType": "",
                "bitrateList": "",
                "bookmarkDate": "",
                "chapter": "40",
                "chargeMode": "",
                "columnChargeMode": "",
                "columnPath": "/MSCP栏目/优酷/电视剧",
                "columnResourcePrice": "",
                "columnServiceId": "",
                "createTime": "",
                "currentChapter": "40",
                "detailLinkUrl": "",
                "detailURI": "",
                "director": [
                    {
                        "directorImageURL": "",
                        "name": "梁昊"
                    }
                ],
                "displayFlags": "",
                "displayRunTime": "",
                "endDateTime": "",
                "favorRating": "0",
                "flagImageUrl": "",
                "folderAssetId": "MANU0000000000050441",
                "folderName": "电视剧",
                "freeChapter": "",
                "hasCollect": "",
                "hasRecommand": "",
                "imageList": [
                    {
                        "height": "358",
                        "posterUrl": "poster_root/20190702/TWSX1562034209304778/266x358/20190702102337417_4859.jpg",
                        "rank": "1",
                        "width": "266"
                    }
                ],
                "imageLocation": "",
                "initialLetter": "",
                "initialLetterToNumber": "",
                "isPackage": "1",
                "openTime": "",
                "orderNumber": "0",
                "originName": "中国大陆",
                "previewAssetId": "",
                "previewProviderId": "",
                "prividerName": "",
                "produceDate": "",
                "producter": "",
                "providerId": "qx_youku",
                "publishDate": "",
                "rating": "",
                "recommandRating": "0.0",
                "recommandTimes": "0",
                "recommendImage": "",
                "recommendLevel": "",
                "remark": "",
                "rentaInfo": "",
                "resourceId": "103758965",
                "resourceType": "0",
                "runtime": "",
                "secondTitleFull": "",
                "selectionChoice": [
                    {
                        "audioType": "",
                        "displayPrice": "0",
                        "format": "HD",
                        "languageSet": "",
                        "rentalPeriod": "0",
                        "screenShape": "",
                        "viewLimit": "0"
                    }
                ],
                "serviceId": "",
                "serviceType": "VOD",
                "showType": "2",
                "startDateTime": "",
                "status": "1",
                "subscription": {
                    "chargeMode": "",
                    "enableTime": "",
                    "expireDateTime": "",
                    "productCode": "",
                    "productName": "",
                    "status": "0",
                    "subscribeTime": "",
                    "subscribeType": ""
                },
                "summarMedium": "",
                "summarvShort": "谜之少女Saori击败各路选手成为当红明星苏达浩的专职保姆，从此以一个特殊的身份进入娱乐圈，苏达浩在强势演艺经纪人蓝岚的包装下，稳坐第一当红明星的宝座，一举一动都是为了维持自己的知名度，苏达浩一开始想尽办法想把Saori赶走，却偏偏每次都反被Saori教训。",
                "tailTime": "",
                "titleBrief": "",
                "titleFull": "我的保姆手册",
                "videoType": "1",
                "viewLevel": "0",
                "year": "0"
            }
        ]
    },
    {
        "custom": "",
        "endDateTime": "",
        "markDateTime": "19/07/30 11:38:13",
        "selectableItem": [
            {
                "actor": "",
                "actorsDisplay": "未知",
                "assetFileList": "",
                "assetId": "TWSX1558601379700533",
                "assetType": "",
                "bitrateList": "",
                "bookmarkDate": "",
                "chapter": "100",
                "chargeMode": "",
                "columnChargeMode": "",
                "columnPath": "/MSCP栏目/优酷/少儿",
                "columnResourcePrice": "",
                "columnServiceId": "",
                "createTime": "",
                "currentChapter": "20",
                "detailLinkUrl": "",
                "detailURI": "",
                "director": [
                    {
                        "directorImageURL": "",
                        "name": "未知"
                    }
                ],
                "displayFlags": "",
                "displayRunTime": "",
                "endDateTime": "",
                "favorRating": "0",
                "flagImageUrl": "",
                "folderAssetId": "MANU0000000000050443",
                "folderName": "少儿",
                "freeChapter": "",
                "hasCollect": "",
                "hasRecommand": "",
                "imageList": [
                    {
                        "height": "358",
                        "posterUrl": "poster_root/20190523/TWSX1558601379700533/266x358/20190523165232135_4743.jpg",
                        "rank": "1",
                        "width": "266"
                    }
                ],
                "imageLocation": "",
                "initialLetter": "",
                "initialLetterToNumber": "",
                "isPackage": "1",
                "openTime": "",
                "orderNumber": "0",
                "originName": "中国大陆",
                "previewAssetId": "",
                "previewProviderId": "",
                "prividerName": "",
                "produceDate": "",
                "producter": [
                    {
                        "name": "未知"
                    }
                ],
                "providerId": "qx_youku",
                "publishDate": "",
                "rating": "",
                "recommandRating": "0.0",
                "recommandTimes": "0",
                "recommendImage": "",
                "recommendLevel": "",
                "remark": "",
                "rentaInfo": "",
                "resourceId": "103744951",
                "resourceType": "0",
                "runtime": "",
                "secondTitleFull": "",
                "selectionChoice": [
                    {
                        "audioType": "",
                        "displayPrice": "0",
                        "format": "HD",
                        "languageSet": "",
                        "rentalPeriod": "0",
                        "screenShape": "",
                        "viewLimit": "0"
                    }
                ],
                "serviceId": "",
                "serviceType": "VOD",
                "showType": "2",
                "startDateTime": "",
                "status": "1",
                "subscription": {
                    "chargeMode": "",
                    "enableTime": "",
                    "expireDateTime": "",
                    "productCode": "",
                    "productName": "",
                    "status": "0",
                    "subscribeTime": "",
                    "subscribeType": ""
                },
                "summarMedium": "",
                "summarvShort": "本动画片故事内容以单元剧为主，在每一集中，拟人化飞机主角乐迪都会飞往世界各地不同的区域，为小朋友们递送他们所需要的包裹，因此观众们将跟随乐迪穿梭于世界各地，看超级飞侠团队运用各自团队的过人能力，帮助小朋友们解决困难。同时，本片中还会呈现世界各地的文化特色，如当地的常用语、当地有名的美食、名人趣事以及有趣的风俗习惯等。",
                "tailTime": "",
                "titleBrief": "",
                "titleFull": "超级飞侠第六季",
                "videoType": "1",
                "viewLevel": "0",
                "year": "0"
            }
        ]
    },
    {
        "custom": "",
        "endDateTime": "",
        "markDateTime": "19/07/30 11:37:44",
        "selectableItem": [
            {
                "actor": "",
                "actorsDisplay": "未知",
                "assetFileList": "",
                "assetId": "TWSX1561273095313342",
                "assetType": "",
                "bitrateList": "",
                "bookmarkDate": "",
                "chapter": "1000",
                "chargeMode": "",
                "columnChargeMode": "",
                "columnPath": "/MSCP栏目/优酷/少儿",
                "columnResourcePrice": "",
                "columnServiceId": "",
                "createTime": "",
                "currentChapter": "260",
                "detailLinkUrl": "",
                "detailURI": "",
                "director": "",
                "displayFlags": "",
                "displayRunTime": "",
                "endDateTime": "",
                "favorRating": "0",
                "flagImageUrl": "",
                "folderAssetId": "MANU0000000000050443",
                "folderName": "少儿",
                "freeChapter": "",
                "hasCollect": "",
                "hasRecommand": "",
                "imageList": [
                    {
                        "height": "358",
                        "posterUrl": "poster_root/20190623/TWSX1561273095313342/266x358/20190623145825498_4828.jpg",
                        "rank": "1",
                        "width": "266"
                    }
                ],
                "imageLocation": "",
                "initialLetter": "",
                "initialLetterToNumber": "",
                "isPackage": "1",
                "openTime": "",
                "orderNumber": "0",
                "originName": "???",
                "previewAssetId": "",
                "previewProviderId": "",
                "prividerName": "",
                "produceDate": "",
                "producter": "",
                "providerId": "qx_youku",
                "publishDate": "",
                "rating": "",
                "recommandRating": "0.0",
                "recommandTimes": "0",
                "recommendImage": "",
                "recommendLevel": "",
                "remark": "",
                "rentaInfo": "",
                "resourceId": "103755345",
                "resourceType": "0",
                "runtime": "",
                "secondTitleFull": "",
                "selectionChoice": [
                    {
                        "audioType": "",
                        "displayPrice": "0",
                        "format": "HD",
                        "languageSet": "",
                        "rentalPeriod": "0",
                        "screenShape": "",
                        "viewLimit": "0"
                    }
                ],
                "serviceId": "",
                "serviceType": "VOD",
                "showType": "2",
                "startDateTime": "",
                "status": "1",
                "subscription": {
                    "chargeMode": "",
                    "enableTime": "",
                    "expireDateTime": "",
                    "productCode": "",
                    "productName": "",
                    "status": "0",
                    "subscribeTime": "",
                    "subscribeType": ""
                },
                "summarMedium": "",
                "summarvShort": "儿歌即儿童歌谣，以幼儿童为接受对象，富有童真童趣，形象生动，易教易懂易记，贴近小朋友的现实生活，是小朋友最喜爱的精神食粮，它对于儿童语言的培养具有极为重要的意义。",
                "tailTime": "",
                "titleBrief": "",
                "titleFull": "开心儿歌",
                "videoType": "1",
                "viewLevel": "10",
                "year": "0"
            }
        ]
    },
    {
        "custom": "",
        "endDateTime": "",
        "markDateTime": "19/07/30 11:23:09",
        "selectableItem": [
            {
                "actor": "",
                "actorsDisplay": "00成龙,ABC,123",
                "assetFileList": "",
                "assetId": "TWSX1564390831653626",
                "assetType": "",
                "bitrateList": "",
                "bookmarkDate": "",
                "chapter": "0",
                "chargeMode": "",
                "columnChargeMode": "",
                "columnPath": "/MSCP栏目/优酷/电影",
                "columnResourcePrice": "",
                "columnServiceId": "",
                "createTime": "",
                "currentChapter": "0",
                "detailLinkUrl": "",
                "detailURI": "",
                "director": [
                    {
                        "directorImageURL": "",
                        "name": "不着调  ZYX"
                    }
                ],
                "displayFlags": "NE",
                "displayRunTime": "367s",
                "endDateTime": "20200729000000",
                "favorRating": "41",
                "flagImageUrl": "/img3.png",
                "folderAssetId": "MANU0000000000050440",
                "folderName": "电影",
                "freeChapter": "",
                "hasCollect": "",
                "hasRecommand": "",
                "imageList": [
                    {
                        "height": "358",
                        "posterUrl": "poster_root/20190729/TWSX1564390831653626/266x358/20190729170212389_0001.jpg",
                        "rank": "1",
                        "width": "266"
                    }
                ],
                "imageLocation": "",
                "initialLetter": "",
                "initialLetterToNumber": "",
                "isPackage": "0",
                "openTime": "",
                "orderNumber": "0",
                "originName": "德国",
                "previewAssetId": "",
                "previewProviderId": "",
                "prividerName": "",
                "produceDate": "",
                "producter": [
                    {
                        "name": "这个是编剧"
                    }
                ],
                "providerId": "cprgtv",
                "publishDate": "",
                "rating": "",
                "recommandRating": "0.0",
                "recommandTimes": "0",
                "recommendImage": "",
                "recommendLevel": "",
                "remark": "",
                "rentaInfo": "",
                "resourceId": "103760202",
                "resourceType": "0",
                "runtime": "00:06:07",
                "secondTitleFull": "",
                "selectionChoice": [
                    {
                        "audioType": "",
                        "displayPrice": "30",
                        "format": "SD",
                        "languageSet": "",
                        "rentalPeriod": "6",
                        "screenShape": "",
                        "viewLimit": "0"
                    }
                ],
                "serviceId": "testbycp",
                "serviceType": "VOD",
                "showType": "1",
                "startDateTime": "20180607000000",
                "status": "1",
                "subscription": {
                    "chargeMode": "",
                    "enableTime": "",
                    "expireDateTime": "",
                    "productCode": "",
                    "productName": "",
                    "status": "0",
                    "subscribeTime": "",
                    "subscribeType": ""
                },
                "summarMedium": "",
                "summarvShort": "节目简介节目简介节目简介节目简介....",
                "tailTime": "",
                "titleBrief": "",
                "titleFull": "Test影片-01",
                "videoType": "0",
                "viewLevel": "13",
                "year": "2018"
            }
        ]
    },
    {
        "custom": "",
        "endDateTime": "",
        "markDateTime": "19/07/30 10:27:02",
        "selectableItem": [
            {
                "actor": "",
                "actorsDisplay": "秋瓷炫;林更新;于荣光",
                "assetFileList": "",
                "assetId": "TWSX1562138219318035",
                "assetType": "",
                "bitrateList": "",
                "bookmarkDate": "",
                "chapter": "42",
                "chargeMode": "",
                "columnChargeMode": "",
                "columnPath": "/MSCP栏目/优酷/电视剧",
                "columnResourcePrice": "",
                "columnServiceId": "",
                "createTime": "",
                "currentChapter": "42",
                "detailLinkUrl": "",
                "detailURI": "",
                "director": [
                    {
                        "directorImageURL": "",
                        "name": "于荣光"
                    }
                ],
                "displayFlags": "",
                "displayRunTime": "",
                "endDateTime": "",
                "favorRating": "0",
                "flagImageUrl": "",
                "folderAssetId": "MANU0000000000050441",
                "folderName": "电视剧",
                "freeChapter": "",
                "hasCollect": "",
                "hasRecommand": "",
                "imageList": [
                    {
                        "height": "358",
                        "posterUrl": "poster_root/20190703/TWSX1562138219318035/266x358/20190703151712379_4862.jpg",
                        "rank": "1",
                        "width": "266"
                    }
                ],
                "imageLocation": "",
                "initialLetter": "",
                "initialLetterToNumber": "",
                "isPackage": "1",
                "openTime": "",
                "orderNumber": "0",
                "originName": "中国香港",
                "previewAssetId": "",
                "previewProviderId": "",
                "prividerName": "",
                "produceDate": "",
                "producter": "",
                "providerId": "qx_youku",
                "publishDate": "",
                "rating": "",
                "recommandRating": "0.0",
                "recommandTimes": "0",
                "recommendImage": "",
                "recommendLevel": "",
                "remark": "",
                "rentaInfo": "",
                "resourceId": "103759746",
                "resourceType": "0",
                "runtime": "",
                "secondTitleFull": "",
                "selectionChoice": [
                    {
                        "audioType": "",
                        "displayPrice": "0",
                        "format": "HD",
                        "languageSet": "",
                        "rentalPeriod": "0",
                        "screenShape": "",
                        "viewLimit": "0"
                    }
                ],
                "serviceId": "",
                "serviceType": "VOD",
                "showType": "2",
                "startDateTime": "",
                "status": "1",
                "subscription": {
                    "chargeMode": "",
                    "enableTime": "",
                    "expireDateTime": "",
                    "productCode": "",
                    "productName": "",
                    "status": "0",
                    "subscribeTime": "",
                    "subscribeType": ""
                },
                "summarMedium": "",
                "summarvShort": "大唐贞元十七年，骠国之王雍羌派遣王子舒难陀带领骠国乐团，离开王都卑谬城，不远千里，远赴大唐献乐。骠国大将军伽罗那野心勃勃，意图劫杀舒难陀，为他篡位铺平道路。 舒难陀因此和伽罗那养子苏决合谋，决定金蝉脱壳，离开乐团大队，并请出身怀绝技的流浪游侠夏云仙和困于天牢的女飞贼夜莎罗，同他一起保护骠国第一舞姬兰玛珊蒂秘密离开骠国前往大唐。",
                "tailTime": "",
                "titleBrief": "",
                "titleFull": "舞乐传奇",
                "videoType": "1",
                "viewLevel": "0",
                "year": "0"
            }
        ]
    }
],
    "newFlag": "N",
    "restartAtToken": "9",
    "totalResults": "10"
}