var imgArr = {
	main_page:[
		"images/main_page/choice.png",
		"images/main_page/choice_focus.png",
		"images/main_page/columns.png",
		"images/main_page/group_focus.png",
		"images/main_page/history.png",
		"images/main_page/history_focus.png",
		"images/main_page/logo.png",
		"images/main_page/mail.png",
		"images/main_page/mail_focus.png",
		
		"images/main_page/news.png",
		"images/main_page/news_focus.png",
		"images/main_page/notice_icon.png",
		"images/main_page/rec_down_focus.png",
		"images/main_page/rec_up_focus.png",
		"images/main_page/recommend.png",
		"images/main_page/recommend_focus.png",
		"images/main_page/reseen.png",
		"images/main_page/reseen_focus.png",
		
		"images/main_page/search.png",
		"images/main_page/search_focus.png",
		"images/main_page/service.png",
		"images/main_page/service_focus.png",
		"images/main_page/smallVideo_focus.png",
		"images/main_page/title.png",
		"images/main_page/title_focus.png"
	],
	tv_page:[
		"images/tv_page/cursor_slider.png",
		"images/tv_page/logo.png",
		"images/tv_page/often_set_box_bg.png",
		"images/tv_page/often_set_box_focus.png",
		"images/tv_page/often_watch_extend1.png",
		"images/tv_page/often_watch_extend2.png",
		"images/tv_page/often_watch_focus.png",
		"images/tv_page/often_watch_set.png",
		"images/tv_page/progress_bar.png",
		"images/tv_page/right_arrow.png",
		
		
		"images/tv_page/strawberry_flag.png",
		"images/tv_page/timeshift.png",
		"images/tv_page/timeshift_focus.png"	
	],
	often_watch:[
		"images/often_watch/check_box_checked.png",
		"images/often_watch/check_box_checked_focus.png",		
		"images/often_watch/check_box_unchecked.png",
		"images/often_watch/check_box_unchecked_focus.png",		
		"images/often_watch/often_order_focus.png",
		"images/often_watch/often_order_move.png",			
		"images/often_watch/order_icon.png"	
	],
	play_tv:[
		"images/play/playtv_cover.png",
		"images/play/pfbar_bg.png",
		"images/play/channel_tag.png",
		"images/play/channelist_bg.png",
		"images/play/channelist_bg_blur.png",
		"images/play/forth_menu_list_blur.png",
		"images/play/forth_menu_list_focus.png",
		"images/play/pf_progress.png",
		"images/play/play_tv_volume_bar.png",
		"images/play/second_menu_list_bg_blur.png",
		"images/play/second_menu_list_bg_focus.png",
		"images/play/third_menu_list_blur1.png",
		"images/play/third_menu_list_blur2.png",
		"images/play/third_menu_list_focus1.png",
		"images/play/third_menu_list_focus2.png",
		"images/play/third_menu_list_focus3.png",
		"images/play/tips_sttv.png",
		"images/channel_order/alert_bg.png",
		"images/channel_order/order_select_bg.png"
	]
};