
const MILLIS_IN_SECOND = 1000
const SECONDS_IN_MINUTE = 60
const ONE_MINUTE = SECONDS_IN_MINUTE * MILLIS_IN_SECOND
const MINUTES_IN_HOUR = 60

export enum Intervals {
  IMMEDIATELY = 5 * MILLIS_IN_SECOND,
  ONE_MIN = ONE_MINUTE,
  FIVE_MIN = 5 * ONE_MINUTE,
  FIFTEEN_MIN = 15 * ONE_MINUTE,
  ONE_HOUR = MINUTES_IN_HOUR * ONE_MINUTE,
  FOUR_HOURS = 4 * MINUTES_IN_HOUR * ONE_MINUTE,
}

